version: '3.1'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.5
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - event-platform
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 10s
      retries: 5

  broker:
    image: confluentinc/cp-server:7.9.5
    hostname: broker
    container_name: broker
    depends_on:
      zookeeper:
        condition: service_healthy
    networks:
      - event-platform
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      ###  SERVER BASICS
      KAFKA_BROKER_ID: 0

      ### SOCKET SERVER SETTINGS
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

      ### LOGS BASICS
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 1

      ### INTERNAL TOPIC SETTINGS
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      ### LOG FLUSH POLICY
      # LOG_FLUXH_INTERVAL_MESSAGES: 10000
      # LOG_FLUSH_INTERVAL_MS: 1000

      ### LOG RETENTION POLICY
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000

      ### ZOOKEEPER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 1800

      ### GROUP COORDINATOR SETTINGS
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 10s
      retries: 5

  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.5
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      zookeeper:
        condition: service_healthy
      broker:
        condition: service_healthy
    networks:
      - event-platform
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8081" ]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  event-platform:
    driver: bridge
